<?php
require_once __DIR__ . '/app/autoload.php';
use App\Core\Database;
use App\Models\Character;
use App\Core\Env;

Env::load(__DIR__ . '/.env');

$db = Database::getInstance();

// 1. Find the book
$stmt = $db->prepare("SELECT id, title FROM books WHERE title LIKE ? OR synopsis LIKE ? LIMIT 1");
$stmt->execute(['%Binding 13%', '%Tommen%']);
$book = $stmt->fetch();

if (!$book) {
    die("No se encontró el libro 'Binding 13' o relacionado con 'Tommen'.\n");
}

$bookId = $book['id'];
echo "Libro encontrado: " . $book['title'] . " (ID: $bookId)\n";

// 2. Define Characters (Generated by me, the AI)
$characters = [
    [
        'name' => 'Johnny Kavanagh',
        'role' => 'Protagonista',
        'description' => 'Estrella del rugby, alto, musculoso, cabello castaño oscuro y ojos verdes intensos. Carismático pero con una carga emocional oculta.',
        'traits' => ['Determinado', 'Protector', 'Carismático'],
        'image_url' => 'https://i.pinimg.com/736x/8a/6e/c3/8a6ec3d6c7d3d8f8c3c8c8c8c8c8c8c8.jpg' // Placeholder or generated lookalike
    ],
    [
        'name' => 'Shannon Lynch',
        'role' => 'Protagonista',
        'description' => 'Pequeña, frágil apariencia, cabello oscuro y ojos azules grandes y expresivos. Tímida y reservada, con cicatrices emocionales y físicas.',
        'traits' => ['Resiliente', 'Tímida', 'Compasiva'],
        'image_url' => 'https://i.pinimg.com/736x/1a/2b/3c/1a2b3c4d5e6f7g8h9i0j1k2l3m4n5o.jpg' // Placeholder
    ],
    [
        'name' => 'Gibsie (Joey)',
        'role' => 'Mejor Amigo',
        'description' => 'El alma de la fiesta, siempre sonriendo, cabello desordenado y energía caótica. Leal hasta la muerte.',
        'traits' => ['Divertido', 'Leal', 'Energético'],
        'image_url' => ''
    ]
];

// 3. Clear existing and Insert
Character::deleteAllByBookId($bookId);

foreach ($characters as $c) {
    Character::create([
        'book_id' => $bookId,
        'name' => $c['name'],
        'role' => $c['role'],
        'description' => $c['description'],
        'traits' => json_encode($c['traits']),
        'image_url' => '', // Leaving empty to use default placeholder or I can try to find a public URL? Better empty for now to avoid broken links.
        'source' => 'Manual AI'
    ]);
}

echo "Personajes insertados correctamente para el libro ID $bookId.\n";